// Mzansi Money Guide - Translation System
// Languages: en, zu, xh, af

const TRANSLATIONS = {
  en: {
    // Nav
    nav_brand: "Mzansi Money Guide",
    nav_home: "Home",
    nav_pathways: "Pathways",
    nav_search: "Search",
    nav_profile: "Profile",
    nav_back: "Back",

    // Home
    home_hero: "Free financial help for every South African",
    home_search_placeholder: "What do you need help with?",
    home_lang_more: "More",
    home_card_personal: "Personal Finance",
    home_card_personal_sub: "Tax, SASSA, UIF, budgeting",
    home_card_personal_steps: "12 steps",
    home_card_start: "Start a Business",
    home_card_start_sub: "Register, open account, comply",
    home_card_start_steps: "8 steps",
    home_card_run: "Run a Business",
    home_card_run_sub: "VAT, payroll, filing taxes",
    home_card_run_steps: "15 steps",
    home_disclaimer: "This guide provides general financial information and does not constitute official legal or financial advice. Always consult with a certified practitioner for your specific needs.",

    // Footer
    footer_quicklinks: "Quick Links",
    footer_support: "Support",
    footer_copyright: "© 2024 Mzansi Money Guide. Multilingual Support (isiZulu, isiXhosa, Afrikaans)",

    // SASSA
    sassa_hero_badge: "Official Support",
    sassa_hero_title: "SASSA Grants & Support",
    sassa_hero_sub: "Simplified guides to help you apply for, manage, and track your social grants with confidence.",
    sassa_free_banner: "This is always FREE to apply. Never pay anyone.",
    sassa_available: "Available Grants",
    sassa_swipe: "Swipe Left",
    sassa_child_name: "Child Support",
    sassa_child_sub: "Monthly support for children",
    sassa_child_elig: "Eligibility: Under 18",
    sassa_old_name: "Old Age Grant",
    sassa_old_sub: "For South Africans 60+",
    sassa_old_elig: "Eligibility: 60+ years",
    sassa_srd_name: "SRD Grant",
    sassa_srd_sub: "Social Relief of Distress",
    sassa_srd_elig: "Unemployed adults",
    sassa_eligible_title: "Am I eligible?",
    sassa_q1: "Are you 60+ years old?",
    sassa_q2: "Is your income below R8k?",
    sassa_q3: "South African citizen?",
    sassa_q_no: "No",
    sassa_q_yes: "Yes",
    sassa_result: "You may qualify for the Old Age Grant of R2,180/month",
    sassa_howto: "How to Apply",
    sassa_step1_title: "Prepare Documents",
    sassa_step1_sub: "Gather your ID book and 3 months bank statement.",
    sassa_step2_title: "Check Requirements",
    sassa_step2_sub: "Perform a self-test of age and income criteria.",
    sassa_step3_title: "Find Nearest Office",
    sassa_step3_sub: "Locate your local SASSA branch office.",
    sassa_step3_link: "VIEW BRANCH MAP",
    sassa_step4_title: "Complete Application",
    sassa_step4_sub: "Fill forms and attend the interview in person.",
    sassa_step5_title: "Wait for Approval",
    sassa_step5_sub: "Final notification will arrive via SMS.",
    sassa_scam_title: "Common Scam Alert",
    sassa_scam_text: "SASSA will never ask you for money or your bank PIN. Be aware of fake websites.",
    sassa_scam_btn: "REPORT A SCAM",
    sassa_whatsapp: "Need help? WhatsApp Us",

    // Business
    biz_badge: "Business Category",
    biz_title: "Business Registration Guide",
    biz_sub: "Everything you need to register your small business with CIPC and start your journey as an entrepreneur in South Africa.",
    biz_start: "Start Guide Now",
    biz_save: "Save for Later",
    biz_lang: "Read this guide in your language:",
    biz_steps_title: "4 Simple Steps to Register",
    biz_s1_title: "Reserve Your Name",
    biz_s1_sub: "You need a unique name. Think of 4 options in case your first choice is taken.",
    biz_s2_title: "Register with CIPC",
    biz_s2_sub: "Complete official registration. You'll need your ID and proof of address. Can be done online or at a self-service terminal.",
    biz_s3_title: "Tax Registration (SARS)",
    biz_s3_sub: "Every business needs a tax number. Most are automatically registered when they register with CIPC.",
    biz_s4_title: "Open a Business Account",
    biz_s4_sub: "Keep personal and business money separate. Many local banks offer free accounts for new small businesses.",
    biz_cta: "Start the CIPC Checklist →",
    biz_feedback: "Recent Feedback",
    biz_related: "Related Topics",

    // Personal Finance
    pf_title: "Personal Finance",
    pf_sub: "Tax, SASSA, UIF, credit and budgeting guides for every South African.",
    pf_tax_title: "Tax & SARS eFiling",
    pf_tax_sub: "File your returns, get a tax number, understand what you owe",
    pf_uif_title: "UIF — Unemployment Fund",
    pf_uif_sub: "Claim unemployment, maternity, illness benefits",
    pf_budget_title: "Budgeting & Savings",
    pf_budget_sub: "50/30/20 rule, stokvels, emergency funds",
    pf_debt_title: "Debt & Credit Score",
    pf_debt_sub: "Understand your score, debt review, National Credit Act rights",
    pf_sassa_link: "SASSA Grants",
    pf_sassa_link_sub: "Apply for social grants",

    // Search
    search_placeholder: "What do you need help with?",
    search_popular: "Popular searches",
    search_browse: "Browse by category",
    search_results: "results for",
    search_none: "No results found",
    search_none_sub: "Try different keywords or",
    search_ask: "ask an expert",

    // Help
    help_title: "Request Financial Support",
    help_sub: "Speak with a local expert who understands South African finances.",
    help_name: "Full Name",
    help_name_ph: "Enter your name",
    help_phone: "Phone Number",
    help_phone_ph: "e.g. 082 123 4567",
    help_topic: "What do you need help with?",
    help_desc: "Brief description",
    help_desc_ph: "Tell us a bit more about your situation...",
    help_submit: "Send Request",
    help_privacy: "Your data is stored securely and never shared.",
    help_certified: "Certified Experts",
    help_certified_sub: "Vetted financial advisors.",
    help_quick: "Quick Response",
    help_quick_sub: "Reply within 2 hours.",
    help_success_title: "Request Sent!",
    help_success_sub: "Our team will contact you within 2 hours. Thank you for reaching out.",
    help_back_home: "Back to Home",
    help_step: "Step",
    help_of: "of",
    help_almost: "Almost there",

    // Topic chips
    topic_sassa: "SASSA Grants",
    topic_tax: "Tax Returns",
    topic_biz: "Business Funding",
    topic_debt: "Debt Review",
    topic_other: "Other",
  },

  zu: {
    nav_brand: "Umhlahlandlela Wezimali",
    nav_home: "Ikhaya",
    nav_pathways: "Izindlela",
    nav_search: "Sesha",
    nav_profile: "Iphrofayili",
    nav_back: "Emuva",
    home_hero: "Usizo lwezimali mahhala kuwo wonke umuntu waseNingizimu Afrika",
    home_search_placeholder: "Ufuna usizo ngani?",
    home_lang_more: "Okunye",
    home_card_personal: "Imali Yomuntu Siqu",
    home_card_personal_sub: "Intela, SASSA, UIF, ukwenza isabelomali",
    home_card_personal_steps: "Izinyathelo eziyi-12",
    home_card_start: "Qala Ibhizinisi",
    home_card_start_sub: "Bhalisa, vula i-akhawunti, landela imithetho",
    home_card_start_steps: "Izinyathelo eziyi-8",
    home_card_run: "Qhuba Ibhizinisi",
    home_card_run_sub: "i-VAT, iholo, ukukhipha intela",
    home_card_run_steps: "Izinyathelo eziyi-15",
    home_disclaimer: "Lo mhlahlandlela uhlinzeka ngolwazi lwezimali jikelele futhi awumeleli izeluleko zomthetho noma zemali. Hlala ubheka nogcwele wezomthetho noma wezimali ezibonakalayo ezimweni zakho.",
    footer_quicklinks: "Izixhumanisi Ezikhawulayo",
    footer_support: "Usizo",
    footer_copyright: "© 2024 Umhlahlandlela Wezimali WaseMzansi. Ukusekela Izizwe Eziningi.",
    sassa_hero_badge: "Ukusekela Okusemthethweni",
    sassa_hero_title: "Izibonelelo ne-SASSA",
    sassa_hero_sub: "Imihlahlandlela elula ukukusiza ukufaka isicelo, ukuphatha, nokulandelela izibonelelo zakho.",
    sassa_free_banner: "Lokhu kuhlala KUMAHHALA ukufaka isicelo. Ungabhadi muntu.",
    sassa_available: "Izibonelelo Ezikhona",
    sassa_swipe: "Shibilika Kwesobunxele",
    sassa_child_name: "Usizo Lomntanakho",
    sassa_child_sub: "Usizo lwanyanga zonke lwabantwana",
    sassa_child_elig: "Ukufanela: Ngaphansi kwe-18",
    sassa_old_name: "Isibonelelo Sabantu Abadala",
    sassa_old_sub: "Abantu baseNingizimu Afrika abane-60+",
    sassa_old_elig: "Ukufanela: Iminyaka eyi-60+",
    sassa_srd_name: "Isibonelelo se-SRD",
    sassa_srd_sub: "Ukwesekwa Kwezenhlalo Ngesikhathi Sokucindezeleka",
    sassa_srd_elig: "Abantu abadala abangenamsebenzi",
    sassa_eligible_title: "Ngiyafanela yini?",
    sassa_q1: "Uniminyaka engama-60 nangaphezulu?",
    sassa_q2: "Ingeniso yakho ingaphansi kuka-R8k?",
    sassa_q3: "Umuntu waseNingizimu Afrika?",
    sassa_q_no: "Cha",
    sassa_q_yes: "Yebo",
    sassa_result: "Ungafanela isibonelelo sabantu abadala se-R2,180 ngenyanga",
    sassa_howto: "Indlela Yokufaka Isicelo",
    sassa_step1_title: "Lungisa Izincwadi",
    sassa_step1_sub: "Qoqa ibhuku lakho le-ID nezinkulumo ze-akhawunti zasebhange zezinyanga ezi-3.",
    sassa_step2_title: "Hlola Izimfuneko",
    sassa_step2_sub: "Zijilele ukuhlola ubudala nezimfuneko zengeniso.",
    sassa_step3_title: "Thola Ihhovisi Elineduze",
    sassa_step3_sub: "Thola igatsha le-SASSA elineduze kuwe.",
    sassa_step3_link: "BONA IKHADI LAMAGATSHA",
    sassa_step4_title: "Gcwalisa Isicelo",
    sassa_step4_sub: "Gcwalisa amafomu uze uxoxe ngemvume wangasibili.",
    sassa_step5_title: "Linda Ukugunyazwa",
    sassa_step5_sub: "Isaziso sokugcina sizofikela nge-SMS.",
    sassa_scam_title: "Isexwayiso Sobuqili Obuqavile",
    sassa_scam_text: "I-SASSA ngeke ikucele imali noma i-PIN yebhange lakho. Qaphela izixhumi zokukhohlisa.",
    sassa_scam_btn: "BIKA UBUQILI",
    sassa_whatsapp: "Udinga usizo? Sithumele ku-WhatsApp",
    biz_badge: "Umkhakha Webhizinisi",
    biz_title: "Umhlahlandlela Wokubhalisa Ibhizinisi",
    biz_sub: "Konke okudingekayo ukubhalisa ibhizinisi lakho elincane ne-CIPC.",
    biz_start: "Qala Umhlahlandlela Manje",
    biz_save: "Gcina Kamuva",
    biz_lang: "Funda lo mhlahlandlela ngolimi lwakho:",
    biz_steps_title: "Izinyathelo Ezili-4 Ezilula Zokubhalisa",
    biz_s1_title: "Gcina Igama Lakho",
    biz_s1_sub: "Udinga igama elizimele. Cinga ngezinketho ezi-4 uma kuhlangatshezwa elinye.",
    biz_s2_title: "Bhalisa ne-CIPC",
    biz_s2_sub: "Gcwalisa ukubhalisa okusemthethweni. Uzodinga i-ID yakho nobufakazi bekheli.",
    biz_s3_title: "Ukubhalisa Kwentela (SARS)",
    biz_s3_sub: "Wonke amabhizinisi adinga inombolo yentela. Amaningi abhalisiwa ngokuzenzekela nge-CIPC.",
    biz_s4_title: "Vula I-Akhawunti Yebhizinisi",
    biz_s4_sub: "Hlukanisa imali yomuntu siqu nemali yebhizinisi. Amaningi amabhange asekhaya avula ama-akhawunti amahhala.",
    biz_cta: "Qala Uhlu Lokuhlola lwe-CIPC →",
    biz_feedback: "Impendulo Yamuva",
    biz_related: "Izihloko Ezihlobene",
    pf_title: "Imali Yomuntu Siqu",
    pf_sub: "Imihlahlandlela yentela, SASSA, UIF, nokhrediti yawo wonke umuntu waseNingizimu Afrika.",
    pf_tax_title: "Intela ne-SARS eFiling",
    pf_tax_sub: "Faka izinkulumo zakho, thola inombolo yentela",
    pf_uif_title: "UIF — Inhlangano Yokuqashwa",
    pf_uif_sub: "Faka isicelo sokungasebenzi, ukubeletha, izinzuzo zokulwela",
    pf_budget_title: "Isabelomali Nokonga",
    pf_budget_sub: "Umthetho we-50/30/20, izistokovela, izimali zokushesha",
    pf_debt_title: "Izikweletu Namanani Akhrediti",
    pf_debt_sub: "Qonda amanani akho, ukubuyekezwa kwezikweletu, amalungelo",
    pf_sassa_link: "Izibonelelo ze-SASSA",
    pf_sassa_link_sub: "Faka isicelo sezibonelelo zezenhlalo",
    search_placeholder: "Ufuna usizo ngani?",
    search_popular: "Izifutho ezivelele",
    search_browse: "Phequla ngokwemkhakha",
    search_results: "imiphumela",
    search_none: "Akukho miphumela etholakele",
    search_none_sub: "Zama amagama ahlukene noma",
    search_ask: "buza ingcweti",
    help_title: "Cela Ukusekela Kwezimali",
    help_sub: "Khuluma nengcweti yasekhaya eqonda izimali zaseNingizimu Afrika.",
    help_name: "Igama Eligcwele",
    help_name_ph: "Faka igama lakho",
    help_phone: "Inombolo Yocingo",
    help_phone_ph: "isib. 082 123 4567",
    help_topic: "Udinga usizo ngani?",
    help_desc: "Incazelo emfushane",
    help_desc_ph: "Sitshele okwengeziwe ngezimo zakho...",
    help_submit: "Thumela Isicelo",
    help_privacy: "Idatha yakho igcinwa ngokuphepha futhi ayibiwa muntu.",
    help_certified: "Izingcweti Ezigunyaziwe",
    help_certified_sub: "Abaluleki bezimali abehlolwe.",
    help_quick: "Impendulo Ekhawulayo",
    help_quick_sub: "Siphendula ngaphakathi kwamahora amabili.",
    help_success_title: "Isicelo Sithumwe!",
    help_success_sub: "Ithimba lethu lizonxhumana nawe ngaphakathi kwamahora amabili.",
    help_back_home: "Buyela Ekhaya",
    help_step: "Isinyathelo",
    help_of: "ku",
    help_almost: "Ufinyelele",
    topic_sassa: "Izibonelelo ze-SASSA",
    topic_tax: "Izinkulumo Zentela",
    topic_biz: "Uxhaso Lwemali Webhizinisi",
    topic_debt: "Ukubuyekezwa Kwezikweletu",
    topic_other: "Okunye",
  },

  xh: {
    nav_brand: "Isicwangciso Semali",
    nav_home: "Ikhaya",
    nav_pathways: "Iindlela",
    nav_search: "Khangela",
    nav_profile: "Iprofayile",
    nav_back: "Emva",
    home_hero: "Uncedo lwemali mahhala kubo bonke abantu baseMzantsi Afrika",
    home_search_placeholder: "Kufuneka uncedo ngantoni?",
    home_lang_more: "Okuninzi",
    home_card_personal: "Imali Yobuqu",
    home_card_personal_sub: "Irhafu, SASSA, UIF, ukwenza isicwangciso semali",
    home_card_personal_steps: "Amanyathelo ali-12",
    home_card_start: "Qala Ishishini",
    home_card_start_sub: "Bhalisa, vula i-akhawunti, landela imithetho",
    home_card_start_steps: "Amanyathelo ali-8",
    home_card_run: "Qhuba Ishishini",
    home_card_run_sub: "i-VAT, imivuzo, ukufaka irhafu",
    home_card_run_steps: "Amanyathelo ali-15",
    home_disclaimer: "Lo mhlahlo unika ulwazi lwemali loluntu futhi awumeleli iingcebiso zomthetho okanye zemali. Hlala ubhekela incazelo yochwephesha.",
    footer_quicklinks: "Iinxibelelwano Ezikhawulezileyo",
    footer_support: "Uncedo",
    footer_copyright: "© 2024 Isicwangciso Semali SaseMzantsi. Ukuxhasa Iilwimi Ezininzi.",
    sassa_hero_badge: "Inkxaso Esemthethweni",
    sassa_hero_title: "Izibonelelo ne-SASSA",
    sassa_hero_sub: "Imihlahlo elula ukukunceda ukufaka isicelo, ukulawula, nokulandela izibonelelo zakho.",
    sassa_free_banner: "Oku kwahlala kuMAHHALA ukufaka isicelo. Musa ukuhlawulela mntu.",
    sassa_available: "Izibonelelo Ezikhona",
    sassa_swipe: "Susa Ekhohlo",
    sassa_child_name: "Inkxaso Yomntwana",
    sassa_child_sub: "Inkxaso yenyanga yonke yabantwana",
    sassa_child_elig: "Ukufaneleka: Ngaphantsi kwe-18",
    sassa_old_name: "Isibonelelo Sabantu Abadala",
    sassa_old_sub: "Abantu baseMzantsi Afrika abane-60+",
    sassa_old_elig: "Ukufaneleka: Iminyaka eyi-60+",
    sassa_srd_name: "Isibonelelo se-SRD",
    sassa_srd_sub: "Uncedo Loluntu Ngexesha Lobunzima",
    sassa_srd_elig: "Abantu abadala abangenamsebenzi",
    sassa_eligible_title: "Ndiyafaneleka na?",
    sassa_q1: "Uneminyaka engama-60 nangaphezulu?",
    sassa_q2: "Ingeniso yakho ingaphantsi kuka-R8k?",
    sassa_q3: "Ummi waseMzantsi Afrika?",
    sassa_q_no: "Hayi",
    sassa_q_yes: "Ewe",
    sassa_result: "Ungafaneleka isibonelelo sabantu abadala se-R2,180 ngenyanga",
    sassa_howto: "Indlela Yokufaka Isicelo",
    sassa_step1_title: "Lungisa Amaxwebhu",
    sassa_step1_sub: "Qokelela incwadi yakho ye-ID nezingxelo zebhanki zezinyanga ezi-3.",
    sassa_step2_title: "Hlola Iimfuno",
    sassa_step2_sub: "Zihlole ngokwakho ubudala kunye neekhritheriya zengeniso.",
    sassa_step3_title: "Fumana Iofisi Ekufutshane",
    sassa_step3_sub: "Fumana isebe le-SASSA ekufutshane nawe.",
    sassa_step3_link: "JONGA IMEPHU YAMASEBE",
    sassa_step4_title: "Gcwalisa Isicelo",
    sassa_step4_sub: "Gcwalisa iifom uze uyivele udibane nomntu.",
    sassa_step5_title: "Linda Imvume",
    sassa_step5_sub: "Isaziso sokugqibela siya kufika nge-SMS.",
    sassa_scam_title: "Isilumkiso Sobuqhophololo Obuqhelekileyo",
    sassa_scam_text: "I-SASSA ayisoze ikucele imali okanye i-PIN yebhanki yakho. Qaphela iisayithi ezikhohlisayo.",
    sassa_scam_btn: "BIKA UBUQHOPHOLOLO",
    sassa_whatsapp: "Ufuna uncedo? Sithumela ku-WhatsApp",
    biz_badge: "Umba Webhizinisi",
    biz_title: "Umhlahlo Wobhaliso Lweshishini",
    biz_sub: "Yonke into oyidingayo ukubhalisa ishishini lakho elincinci ne-CIPC.",
    biz_start: "Qala Umhlahlo Ngoku",
    biz_save: "Gcina Kamva",
    biz_lang: "Funda lo mhlahlo ngolwimi lwakho:",
    biz_steps_title: "Amanyathelo Ali-4 Alula Okubhalisa",
    biz_s1_title: "Gcina Igama Lakho",
    biz_s1_sub: "Ufuna igama elikhethekileyo. Cinga ngezinketho ezi-4.",
    biz_s2_title: "Bhalisa ne-CIPC",
    biz_s2_sub: "Gcwalisa ubhaliso olusemthethweni. Uya kufuna i-ID yakho nobungqina bekheli.",
    biz_s3_title: "Ubhaliso Lwerhafu (SARS)",
    biz_s3_sub: "Wonke amashishini afuna inombolo yerhafu. Uninzi lubhaliswa ngokuzenzekelayo ne-CIPC.",
    biz_s4_title: "Vula I-Akhawunti Yeshishini",
    biz_s4_sub: "Ahlule imali yobuqu nemali yeshishini. Iibhanki ezininzi zivula ii-akhawunti zamahhala.",
    biz_cta: "Qala Uluhlu Lwe-CIPC →",
    biz_feedback: "Impendulo Yamva Nje",
    biz_related: "Izihloko Ezinxulumeneyo",
    pf_title: "Imali Yobuqu",
    pf_sub: "Imihlahlo yerhafu, SASSA, UIF, nokredi kubo bonke abantu baseMzantsi Afrika.",
    pf_tax_title: "Irhafu ne-SARS eFiling",
    pf_tax_sub: "Faka iingxelo zakho, fumana inombolo yerhafu",
    pf_uif_title: "UIF — Isinxibo Sokungasebenzi",
    pf_uif_sub: "Faka isicelo sokusilela emsebenzini, ukuzala, izibonelelo zokugula",
    pf_budget_title: "Isicwangciso Semali Nokonga",
    pf_budget_sub: "Umthetho we-50/30/20, iistokveli, imali yohlaseleko",
    pf_debt_title: "Amatyala Nesi-Score Sekredi",
    pf_debt_sub: "Qonda isi-score sakho, ukubuyekezwa kwamatyala, amalungelo",
    pf_sassa_link: "Izibonelelo ze-SASSA",
    pf_sassa_link_sub: "Faka isicelo sezibonelelo zentlalontle",
    search_placeholder: "Kufuneka uncedo ngantoni?",
    search_popular: "Uphendlo oluxhaphakileyo",
    search_browse: "Jonga ngokwemba",
    search_results: "imiphumo",
    search_none: "Akukho miphumo efunyenweyo",
    search_none_sub: "Zama amagama ahlukeneyo okanye",
    search_ask: "buza uchwephesha",
    help_title: "Cela Inkxaso Yemali",
    help_sub: "Thetha nochwephesha wasekhaya oqonda imali yaseMzantsi Afrika.",
    help_name: "Igama Eligcweleyo",
    help_name_ph: "Faka igama lakho",
    help_phone: "Inombolo Yefowuni",
    help_phone_ph: "umz. 082 123 4567",
    help_topic: "Kufuneka uncedo ngantoni?",
    help_desc: "Ingxelo emfutshane",
    help_desc_ph: "Sitshintshe okuninzi ngimeko yakho...",
    help_submit: "Thumela Isicelo",
    help_privacy: "Idatha yakho igcinwa ngokukhuselekileyo futhi ayabelwanga mntu.",
    help_certified: "Oochwephesha Abagunyaziweyo",
    help_certified_sub: "Abaluleki bemali abagqitiweyo.",
    help_quick: "Impendulo Ekhawulezileyo",
    help_quick_sub: "Siphendula ngaphakathi kweeyure ezimbini.",
    help_success_title: "Isicelo Sithunyiwe!",
    help_success_sub: "Iqela lethu liya kuqhagamshelana nawe ngaphakathi kweeyure ezimbini.",
    help_back_home: "Buyela Ekhaya",
    help_step: "Inyathelo",
    help_of: "ku",
    help_almost: "Kufuphi",
    topic_sassa: "Izibonelelo ze-SASSA",
    topic_tax: "Iingxelo Zerhafu",
    topic_biz: "Inkxaso Yemali Yeshishini",
    topic_debt: "Ukubuyekezwa Kwamatyala",
    topic_other: "Okunye",
  },

  af: {
    nav_brand: "Mzansi Geldgids",
    nav_home: "Tuis",
    nav_pathways: "Paaie",
    nav_search: "Soek",
    nav_profile: "Profiel",
    nav_back: "Terug",
    home_hero: "Gratis finansiële hulp vir elke Suid-Afrikaner",
    home_search_placeholder: "Waarmee kan ons jou help?",
    home_lang_more: "Meer",
    home_card_personal: "Persoonlike Finansies",
    home_card_personal_sub: "Belasting, SASSA, UIF, begroting",
    home_card_personal_steps: "12 stappe",
    home_card_start: "Begin 'n Besigheid",
    home_card_start_sub: "Registreer, maak rekening oop, voldoen",
    home_card_start_steps: "8 stappe",
    home_card_run: "Bestuur 'n Besigheid",
    home_card_run_sub: "BTW, salarislyste, belastingaangifte",
    home_card_run_steps: "15 stappe",
    home_disclaimer: "Hierdie gids verskaf algemene finansiële inligting en verteenwoordig nie amptelike regs- of finansiële advies nie. Raadpleeg altyd 'n gesertifiseerde praktisyn vir jou spesifieke behoeftes.",
    footer_quicklinks: "Vinnige Skakels",
    footer_support: "Ondersteuning",
    footer_copyright: "© 2024 Mzansi Geldgids. Meertalige Ondersteuning (isiZulu, isiXhosa, Afrikaans)",
    sassa_hero_badge: "Amptelike Ondersteuning",
    sassa_hero_title: "SASSA-toelaes en Ondersteuning",
    sassa_hero_sub: "Vereenvoudigde gidse om jou te help om jou sosiale toelaes met vertroue aan te vra, te bestuur en te volg.",
    sassa_free_banner: "Dit is altyd GRATIS om aansoek te doen. Betaal nooit iemand nie.",
    sassa_available: "Beskikbare Toelaes",
    sassa_swipe: "Vee Links",
    sassa_child_name: "Kinderondersteuning",
    sassa_child_sub: "Maandelikse ondersteuning vir kinders",
    sassa_child_elig: "Geskiktheid: Onder 18",
    sassa_old_name: "Ouderdomstoelae",
    sassa_old_sub: "Vir Suid-Afrikaners 60+",
    sassa_old_elig: "Geskiktheid: 60+ jaar",
    sassa_srd_name: "SRD-toelae",
    sassa_srd_sub: "Sosiale Verligting van Nood",
    sassa_srd_elig: "Werklose volwassenes",
    sassa_eligible_title: "Is ek geskik?",
    sassa_q1: "Is jy 60 jaar of ouer?",
    sassa_q2: "Is jou inkomste onder R8k?",
    sassa_q3: "Suid-Afrikaanse burger?",
    sassa_q_no: "Nee",
    sassa_q_yes: "Ja",
    sassa_result: "Jy kwalifiseer moontlik vir die Ouderdomstoelae van R2,180/maand",
    sassa_howto: "Hoe om aansoek te doen",
    sassa_step1_title: "Berei Dokumente Voor",
    sassa_step1_sub: "Versamel jou ID-boek en 3 maande bankstate.",
    sassa_step2_title: "Kontroleer Vereistes",
    sassa_step2_sub: "Doen 'n selftoets van ouderdom en inkomstekriteria.",
    sassa_step3_title: "Vind Naaste Kantoor",
    sassa_step3_sub: "Vind jou plaaslike SASSA-tak.",
    sassa_step3_link: "BEKYK TAKKAART",
    sassa_step4_title: "Voltooi Aansoek",
    sassa_step4_sub: "Vul vorms in en woon die onderhoud persoonlik by.",
    sassa_step5_title: "Wag vir Goedkeuring",
    sassa_step5_sub: "Finale kennisgewing sal per SMS aankom.",
    sassa_scam_title: "Algemene Bedrogwaarskuwing",
    sassa_scam_text: "SASSA sal jou nooit vra vir geld of jou bank-PIN nie. Wees bewus van vals webwerwe.",
    sassa_scam_btn: "RAPPORTEER 'N BEDROG",
    sassa_whatsapp: "Hulp nodig? WhatsApp Ons",
    biz_badge: "Besigheidskategorie",
    biz_title: "Besigheidsregistrasiegids",
    biz_sub: "Alles wat jy nodig het om jou klein besigheid by CIPC te registreer.",
    biz_start: "Begin Nou Gids",
    biz_save: "Stoor vir Later",
    biz_lang: "Lees hierdie gids in jou taal:",
    biz_steps_title: "4 Eenvoudige Stappe om te Registreer",
    biz_s1_title: "Reserveer Jou Naam",
    biz_s1_sub: "Jy benodig 'n unieke naam. Dink aan 4 opsies ingeval jou eerste keuse al geneem is.",
    biz_s2_title: "Registreer by CIPC",
    biz_s2_sub: "Voltooi amptelike registrasie. Jy benodig jou ID en bewys van adres.",
    biz_s3_title: "Belastingregistrasie (SARS)",
    biz_s3_sub: "Elke besigheid benodig 'n belastingnommer. Die meeste word outomaties geregistreer met CIPC.",
    biz_s4_title: "Maak 'n Besigheidsrekening Oop",
    biz_s4_sub: "Hou persoonlike en besigheidsgeld apart. Baie plaaslike banke bied gratis rekeninge aan.",
    biz_cta: "Begin die CIPC-Kontrolelys →",
    biz_feedback: "Onlangse Terugvoer",
    biz_related: "Verwante Onderwerpe",
    pf_title: "Persoonlike Finansies",
    pf_sub: "Belasting, SASSA, UIF, krediet en begrotingsgidse vir elke Suid-Afrikaner.",
    pf_tax_title: "Belasting en SARS eFiling",
    pf_tax_sub: "Dien jou opgawes in, kry 'n belastingnommer",
    pf_uif_title: "UIF — Werkloosheidsfonds",
    pf_uif_sub: "Dien aansoek in vir werkloosheid, moederskap, siektevoordele",
    pf_budget_title: "Begroting en Spaar",
    pf_budget_sub: "50/30/20-reël, stokvels, noodfondse",
    pf_debt_title: "Skuld en Kredietpunt",
    pf_debt_sub: "Verstaan jou punt, skuldhersiening, Nasionale Kredietwet-regte",
    pf_sassa_link: "SASSA-toelaes",
    pf_sassa_link_sub: "Dien aansoek in vir sosiale toelaes",
    search_placeholder: "Waarmee kan ons jou help?",
    search_popular: "Gewilde soektogte",
    search_browse: "Blaai per kategorie",
    search_results: "resultate vir",
    search_none: "Geen resultate gevind nie",
    search_none_sub: "Probeer verskillende sleutelwoorde of",
    search_ask: "vra 'n deskundige",
    help_title: "Versoek Finansiële Ondersteuning",
    help_sub: "Praat met 'n plaaslike deskundige wat Suid-Afrikaanse finansies verstaan.",
    help_name: "Volle Naam",
    help_name_ph: "Voer jou naam in",
    help_phone: "Telefoonnommer",
    help_phone_ph: "bv. 082 123 4567",
    help_topic: "Waarmee het jy hulp nodig?",
    help_desc: "Kort beskrywing",
    help_desc_ph: "Vertel ons meer oor jou situasie...",
    help_submit: "Stuur Versoek",
    help_privacy: "Jou data word veilig gestoor en nooit gedeel nie.",
    help_certified: "Gesertifiseerde Deskundiges",
    help_certified_sub: "Geverifieerde finansiële adviseurs.",
    help_quick: "Vinnige Respons",
    help_quick_sub: "Ons antwoord binne 2 uur.",
    help_success_title: "Versoek Gestuur!",
    help_success_sub: "Ons span sal jou binne 2 uur kontak.",
    help_back_home: "Terug na Tuis",
    help_step: "Stap",
    help_of: "van",
    help_almost: "Amper daar",
    topic_sassa: "SASSA-toelaes",
    topic_tax: "Belastingopgawes",
    topic_biz: "Besigheidsbefondsing",
    topic_debt: "Skuldhersiening",
    topic_other: "Ander",
  }
};

// Current language state
let currentLang = localStorage.getItem('mmg_lang') || 'en';

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('mmg_lang', lang);
  applyTranslations();
  updateLangButtons();
}

function t(key) {
  return (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) 
    || (TRANSLATIONS['en'] && TRANSLATIONS['en'][key]) 
    || key;
}

function applyTranslations() {
  document.querySelectorAll('[data-t]').forEach(el => {
    const key = el.getAttribute('data-t');
    const attr = el.getAttribute('data-t-attr');
    if (attr) {
      el.setAttribute(attr, t(key));
    } else {
      el.textContent = t(key);
    }
  });
}

function updateLangButtons() {
  document.querySelectorAll('[data-lang]').forEach(btn => {
    const lang = btn.getAttribute('data-lang');
    if (lang === currentLang) {
      btn.classList.remove('bg-surface-container-high', 'text-on-surface-variant');
      btn.classList.add('bg-primary', 'text-on-primary');
    } else {
      btn.classList.remove('bg-primary', 'text-on-primary');
      btn.classList.add('bg-surface-container-high', 'text-on-surface-variant');
    }
  });
}

// Auto-apply on DOM ready
document.addEventListener('DOMContentLoaded', () => {
  applyTranslations();
  updateLangButtons();
});
